<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

<script>
  //Promise.all方法用于将多个 Promise 实例，包装成一个新的 Promise 实例。
  //Promise.all方法的参数可以不是数组，但必须具有 Iterator 接口，且返回的每个成员都是 Promise 实例
  //只有所有promise实例的状态都变成fulfilled，新的Promise实例的状态才会变成fulfilled，此时所有的参数实例的返回值组成一个数组，传递给新的Promise实例的回调函数。
  //只要所有promise实例之中有一个被rejected，新的Promise实例的状态就变成rejected，此时第一个被reject的实例的返回值，会传递给新的Promise实例的回调函数。

  const promise1 = new Promise((resolve, reject) => {
    return setTimeout(() => resolve('1'), 2000);
  })

  const promise2 = new Promise((resolve, reject) => {
    return setTimeout(() => resolve('2'), 2000);
  })

  Promise.all([
    promise1,
    promise2
  ])
    .then((results) => {
      console.log('success', results);
    })
    .catch((error) => {
      console.log('error', error);
    })

    //'success' ['1', '2']

  
  const promise3 = new Promise((resolve, reject) => {
    return setTimeout(() => {
      console.log('promise3');
      reject('3')
      }, 2000);
  })

  const promise4 = new Promise((resolve, reject) => {
    return setTimeout(() => {
      console.log('promise4')
      resolve('4');
      }, 2000);
  })

  Promise.all([
    promise3,
    promise4
  ])
    .then((results) => {
      console.log('success', results);
    })
    .catch((error) => {
      console.log('error', error);
    })

  //'promise3'
  //'error' 3
  //'promise4'


  //如果作为参数的 Promise 实例，自己定义了catch方法，那么它一旦被rejected，并不会触发Promise.all()的catch方法
  const promise5 = new Promise((resolve, reject) => {
    return setTimeout(() => {
      console.log('promise5');
      reject('5')
      }, 2000);
  })
  .then(result => result)
  .catch(error => error);

  const promise6 = new Promise((resolve, reject) => {
    return setTimeout(() => {
      console.log('promise6')
      resolve('6');
      }, 2000);
  })
  .then(result => result)
  .catch(error => error);

  Promise.all([
    promise5,
    promise6
  ])
    .then((results) => {
      console.log('success', results);
    })
    .catch((error) => {
      console.log('error', error);
    })
    //'promise5'
    //'promise6'
    //'success' ["5", "6"]
</script>
</body>
</html>